services:
  db:
    image: postgres:15-alpine
    container_name: lms-postgres
    restart: always
    environment:
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
      POSTGRES_DB: lms_database
    ports:
      - "5436:5432" # Host:Container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lms-app:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://lms_user:lms_password@db:5432/lms_database?sslmode=disable
        - DIRECT_URL=postgresql://lms_user:lms_password@db:5432/lms_database?sslmode=disable
    container_name: lms-nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@db:5432/lms_database?sslmode=disable
    depends_on:
      - db

volumes:
  postgres_data: