"use client";

import Link from "next/link";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { motion } from "framer-motion";
import {
  MoveRight,
  Bot,
  BarChart3,
  GraduationCap,
  Sparkles,
  Zap,
  TrendingUp,
} from "lucide-react";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-zinc-50 scroll-smooth">
      <Navbar />

      {/* HERO SECTION */}
      <section className="relative pt-24 pb-20 md:pt-32 md:pb-28 overflow-hidden">
        {/* Premium background glow effects - pointer-events-none to prevent blocking clicks */}
        <div className="absolute inset-0 bg-[radial-gradient(at_top_right,#6366f1_0%,transparent_70%)] opacity-10 pointer-events-none" />
        <div className="absolute inset-0 bg-[radial-gradient(at_bottom_left,#a855f7_0%,transparent_70%)] opacity-10 pointer-events-none" />

        {/* Animated orbs - pointer-events-none */}
        <div className="absolute left-10 top-20 h-96 w-96 rounded-full bg-indigo-400/10 blur-3xl animate-[pulse_10s_infinite] pointer-events-none" />
        <div className="absolute right-10 bottom-12 h-80 w-80 rounded-full bg-violet-400/10 blur-3xl animate-[pulse_14s_infinite] pointer-events-none" />

        <div className="max-w-7xl mx-auto px-6 lg:px-8 relative z-10">
          <div className="grid lg:grid-cols-12 gap-16 items-center">
            {/* Left content */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="lg:col-span-7 space-y-8"
            >
              {/* Badge */}
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.2 }}
                className="inline-flex items-center gap-2 rounded-3xl bg-white/80 backdrop-blur-xl px-6 py-3 text-sm font-semibold text-zinc-700 shadow-inner ring-1 ring-inset ring-indigo-200"
              >
                <Sparkles className="h-4 w-4 text-violet-500" />
                Now powered by Gemini 1.5 Pro
              </motion.div>

              {/* Gradient headline */}
              <h1 className="text-6xl md:text-7xl font-semibold tracking-tighter leading-none text-zinc-900">
                Adaptive{" "}
                <span className="bg-linear-to-r from-indigo-600 via-violet-600 to-blue-600 bg-clip-text text-transparent">
                  AI LMS
                </span>
              </h1>

              <p className="max-w-xl text-2xl text-zinc-600 leading-tight">
                Personalized learning paths generated by Google Gemini. Learn
                faster, smarter, and at your own pace.
              </p>

              {/* CTA buttons */}
              <div className="flex flex-col sm:flex-row gap-4 pt-4">
                <motion.div
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  transition={{ type: "spring", stiffness: 400, damping: 17 }}
                >
                  <Link
                    href="/register"
                    className="group inline-flex h-14 items-center justify-center gap-3 rounded-3xl bg-linear-to-r from-indigo-600 to-violet-600 px-10 font-semibold text-white text-lg shadow-2xl shadow-indigo-500/30 hover:shadow-indigo-500/40 transition-all duration-300 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                    aria-label="Start learning for free"
                  >
                    Start Learning Free
                    <MoveRight className="h-5 w-5 transition-transform group-active:translate-x-1" />
                  </Link>
                </motion.div>

                <motion.div
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  transition={{ type: "spring", stiffness: 400, damping: 17 }}
                >
                  <Link
                    href="#features"
                    className="inline-flex h-14 items-center justify-center rounded-3xl border border-zinc-200 bg-white px-8 font-semibold text-zinc-700 text-lg hover:bg-zinc-50 transition-all duration-300 focus-visible:outline-offset-2 focus-visible:outline-zinc-400"
                    aria-label="View features"
                  >
                    View Features
                  </Link>
                </motion.div>
              </div>

              {/* Trust signals */}
              <div className="flex items-center gap-8 text-sm text-zinc-500 pt-4">
                <div className="flex -space-x-4">
                  <div className="h-8 w-8 rounded-2xl bg-linear-to-br from-blue-100 to-indigo-100 flex items-center justify-center text-xs font-medium ring-2 ring-white">
                    G
                  </div>
                  <div className="h-8 w-8 rounded-2xl bg-linear-to-br from-violet-100 to-purple-100 flex items-center justify-center text-xs font-medium ring-2 ring-white">
                    V
                  </div>
                </div>
                <p className="leading-none">
                  Trusted by 8,400+ students
                  <br />
                  and 240 institutions
                </p>
              </div>
            </motion.div>

            {/* Right visual mock */}
            <motion.div
              initial={{ opacity: 0, x: 40 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.9, delay: 0.4 }}
              className="lg:col-span-5 relative hidden lg:flex justify-end"
            >
              <div className="relative w-full max-w-md">
                <div className="absolute -inset-6 bg-linear-to-br from-indigo-400/20 to-violet-400/20 blur-3xl rounded-3xl -z-10 pointer-events-none" />
                <div className="relative bg-white/70 backdrop-blur-2xl border border-white shadow-2xl rounded-3xl p-2">
                  <div className="bg-zinc-950 rounded-3xl overflow-hidden">
                    <div className="px-6 pt-6 pb-4 flex items-center justify-between border-b border-white/10">
                      <div className="flex items-center gap-3">
                        <div className="h-8 w-8 rounded-2xl bg-linear-to-br from-indigo-500 to-violet-500 flex items-center justify-center">
                          <Bot className="h-4 w-4 text-white" />
                        </div>
                        <div className="text-white">
                          <p className="font-medium text-sm">AI Study Coach</p>
                          <p className="text-zinc-400 text-xs">Gemini • Live</p>
                        </div>
                      </div>
                      <div className="px-4 py-1 text-xs font-medium bg-emerald-400/10 text-emerald-400 rounded-3xl">
                        In progress
                      </div>
                    </div>

                    <div className="p-6 space-y-6">
                      <div className="bg-white/10 rounded-2xl p-4 text-white">
                        <div className="flex justify-between text-sm mb-3">
                          <span className="font-medium">30-day AI Roadmap</span>
                          <span className="text-emerald-400">92% complete</span>
                        </div>
                        <div className="h-2 bg-white/20 rounded-full overflow-hidden mb-4">
                          <div className="h-2 w-[92%] bg-linear-to-r from-emerald-400 to-cyan-400 rounded-full" />
                        </div>
                        <div className="flex gap-2 text-xs">
                          <div className="bg-white/10 px-3 py-1 rounded-2xl">
                            Day 12 • Neural Networks
                          </div>
                          <div className="bg-emerald-400/20 px-3 py-1 rounded-2xl text-emerald-300">
                            Next: Transformers
                          </div>
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                        <div className="bg-white/10 rounded-2xl p-4">
                          <p className="text-xs text-zinc-400">
                            Current streak
                          </p>
                          <p className="text-4xl font-semibold text-white mt-1">
                            14 days
                          </p>
                        </div>
                        <div className="bg-white/10 rounded-2xl p-4">
                          <p className="text-xs text-zinc-400">Mastery score</p>
                          <p className="text-4xl font-semibold text-white mt-1">
                            87%
                          </p>
                        </div>
                      </div>

                      <div className="text-center text-xs text-zinc-400 font-medium flex items-center justify-center gap-2">
                        <div className="h-px w-8 bg-white/30" />
                        Powered by Gemini
                        <div className="h-px w-8 bg-white/30" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* FEATURES SECTION */}
      <section id="features" className="scroll-mt-24 py-24 bg-white">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <span className="px-4 py-2 text-xs font-semibold tracking-widest bg-indigo-100 text-indigo-700 rounded-3xl">
              POWERFUL AI FEATURES
            </span>
            <h2 className="text-4xl font-semibold tracking-tight text-zinc-900 mt-4">
              Built for modern learning
            </h2>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              whileHover={{ y: -12, transition: { duration: 0.3 } }}
              className="group bg-white border border-zinc-100 rounded-3xl p-10 shadow-sm hover:shadow-2xl transition-all duration-300"
            >
              <div className="h-14 w-14 rounded-2xl bg-linear-to-br from-indigo-100 to-violet-100 flex items-center justify-center mb-8 group-hover:scale-110 transition-transform">
                <Bot className="h-8 w-8 text-indigo-600" />
              </div>
              <h3 className="font-semibold text-2xl text-zinc-900">
                AI Study Plans
              </h3>
              <p className="mt-4 text-zinc-600 leading-relaxed">
                Enter any topic and our Gemini integration creates a structured
                30-day roadmap tailored to your specific goals.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              whileHover={{ y: -12, transition: { duration: 0.3 } }}
              className="group bg-white border border-zinc-100 rounded-3xl p-10 shadow-sm hover:shadow-2xl transition-all duration-300"
            >
              <div className="h-14 w-14 rounded-2xl bg-linear-to-br from-indigo-100 to-violet-100 flex items-center justify-center mb-8 group-hover:scale-110 transition-transform">
                <BarChart3 className="h-8 w-8 text-indigo-600" />
              </div>
              <h3 className="font-semibold text-2xl text-zinc-900">
                Progress Tracking
              </h3>
              <p className="mt-4 text-zinc-600 leading-relaxed">
                Advanced analytics for teachers to monitor student engagement
                and performance metrics in real-time.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2 }}
              whileHover={{ y: -12, transition: { duration: 0.3 } }}
              className="group bg-white border border-zinc-100 rounded-3xl p-10 shadow-sm hover:shadow-2xl transition-all duration-300"
            >
              <div className="h-14 w-14 rounded-2xl bg-linear-to-br from-indigo-100 to-violet-100 flex items-center justify-center mb-8 group-hover:scale-110 transition-transform">
                <GraduationCap className="h-8 w-8 text-indigo-600" />
              </div>
              <h3 className="font-semibold text-2xl text-zinc-900">
                Smart Assessments
              </h3>
              <p className="mt-4 text-zinc-600 leading-relaxed">
                Dynamic quizzes that adapt difficulty levels based on your
                previous answers for a more efficient learning curve.
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* HOW IT WORKS SECTION */}
      <section className="py-24 bg-zinc-50">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-xl mx-auto text-center mb-16"
          >
            <h2 className="text-4xl font-semibold tracking-tight text-zinc-900">
              How it works in 3 steps
            </h2>
            <p className="mt-4 text-zinc-600">
              From idea to mastery in minutes with AI
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            <motion.div
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              whileHover={{ scale: 1.03 }}
              className="group bg-white rounded-3xl p-8 border border-transparent hover:border-zinc-100 hover:shadow-xl transition-all"
            >
              <div className="flex items-center justify-between">
                <div className="text-7xl font-bold text-zinc-100 group-hover:text-indigo-100 transition-colors">
                  01
                </div>
                <div className="h-12 w-12 flex items-center justify-center bg-linear-to-br from-amber-100 to-yellow-100 rounded-2xl group-hover:rotate-12 transition-transform">
                  <Zap className="h-7 w-7 text-amber-500" />
                </div>
              </div>
              <h4 className="text-2xl font-semibold mt-10">Share your goal</h4>
              <p className="mt-3 text-zinc-600">
                Tell Gemini what you want to master. Any topic, any level.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.15 }}
              whileHover={{ scale: 1.03 }}
              className="group bg-white rounded-3xl p-8 border border-transparent hover:border-zinc-100 hover:shadow-xl transition-all"
            >
              <div className="flex items-center justify-between">
                <div className="text-7xl font-bold text-zinc-100 group-hover:text-indigo-100 transition-colors">
                  02
                </div>
                <div className="h-12 w-12 flex items-center justify-center bg-linear-to-br from-violet-100 to-indigo-100 rounded-2xl group-hover:rotate-12 transition-transform">
                  <Bot className="h-7 w-7 text-violet-600" />
                </div>
              </div>
              <h4 className="text-2xl font-semibold mt-10">
                AI builds your path
              </h4>
              <p className="mt-3 text-zinc-600">
                Gemini instantly creates a personalized 30-day roadmap with
                lessons, quizzes &amp; milestones.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.3 }}
              whileHover={{ scale: 1.03 }}
              className="group bg-white rounded-3xl p-8 border border-transparent hover:border-zinc-100 hover:shadow-xl transition-all"
            >
              <div className="flex items-center justify-between">
                <div className="text-7xl font-bold text-zinc-100 group-hover:text-indigo-100 transition-colors">
                  03
                </div>
                <div className="h-12 w-12 flex items-center justify-center bg-linear-to-br from-cyan-100 to-teal-100 rounded-2xl group-hover:rotate-12 transition-transform">
                  <TrendingUp className="h-7 w-7 text-cyan-600" />
                </div>
              </div>
              <h4 className="text-2xl font-semibold mt-10">
                Learn &amp; track progress
              </h4>
              <p className="mt-3 text-zinc-600">
                Adaptive quizzes, real-time insights, and teacher dashboards
                keep you on track.
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* FINAL CTA SECTION */}
      <section className="py-20 bg-linear-to-r from-indigo-600 to-violet-600 text-white">
        <div className="max-w-7xl mx-auto px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-2xl mx-auto"
          >
            <h2 className="text-4xl font-semibold tracking-tight">
              Ready to transform how you learn?
            </h2>
            <p className="mt-4 text-xl opacity-90">
              Join thousands of learners already using AI-powered education.
            </p>

            <motion.div
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="mt-10 inline-block"
            >
              <Link
                href="/register"
                className="inline-flex h-14 items-center gap-3 rounded-3xl bg-white text-zinc-900 px-12 font-semibold text-lg shadow-2xl transition-all hover:shadow-white/30 focus-visible:outline-offset-2 focus-visible:outline-white"
                aria-label="Get started for free"
              >
                Get started for free
                <MoveRight className="h-5 w-5" />
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
