import Link from "next/link";
import { MoveRight, Bot, BarChart3, GraduationCap, Sparkles, ArrowRight } from "lucide-react";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-16">
        <div className="absolute inset-0 bg-hero-gradient opacity-95" />
        <div className="relative max-w-7xl mx-auto px-6">
          <div className="mx-auto max-w-3xl text-center space-y-6 py-20">
            <div className="inline-flex items-center gap-2 rounded-full bg-white/15 backdrop-blur-sm border border-white/20 px-4 py-2 text-sm font-medium text-white animate-fade-in">
              <Sparkles className="h-4 w-4" />
              Now powered by Gemini 1.5 Pro
            </div>

            <h1 className="text-5xl md:text-6xl font-extrabold tracking-tight animate-fade-in animation-delay-200">
              Adaptive <span className="text-white drop-shadow-lg">AI LMS</span>
            </h1>

            <p className="text-lg text-white/90 leading-relaxed animate-fade-in animation-delay-400">
              Personalized learning paths generated by Google Gemini. Learn
              faster, smarter, and at your own pace with AI-tailored study plans.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4 animate-fade-in animation-delay-400">
              <Link
                href="/register"
                className="group inline-flex items-center justify-center gap-2 rounded-xl bg-white text-slate-900 px-8 py-3 font-semibold shadow-lg shadow-slate-900/10 hover:bg-slate-50 hover:shadow-xl transition-all duration-300 hover:scale-105"
              >
                Start Learning Free
                <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
              </Link>
              <Link
                href="#features"
                className="inline-flex items-center justify-center rounded-xl border border-white/40 bg-white/10 text-white px-8 py-3 font-semibold hover:bg-white/20 hover:border-white/60 transition-all duration-300 backdrop-blur-sm"
              >
                View Features
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Feature Cards Section */}
      <section id="features" className="py-24">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-4">
              Why Choose AI-LMS?
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-300 max-w-2xl mx-auto">
              Experience the future of education with our AI-powered learning platform
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {/* AI Study Plans */}
            <div className="group bg-white dark:bg-slate-800 p-8 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-700 hover:border-primary/40 hover:shadow-xl transition-all duration-300 hover:-translate-y-2 animate-fade-in">
              <div className="bg-primary/10 w-12 h-12 rounded-xl flex items-center justify-center mb-6 group-hover:bg-primary group-hover:scale-110 transition-all duration-300">
                <Bot className="h-6 w-6 text-primary group-hover:text-white" />
              </div>
              <h3 className="font-bold text-xl text-slate-900 dark:text-white mb-3">
                AI Study Plans
              </h3>
              <p className="text-slate-600 dark:text-slate-300 mt-3 leading-relaxed">
                Enter any topic and our Gemini integration creates a structured
                30-day roadmap tailored to your specific goals.
              </p>
            </div>

            {/* Teacher Insights */}
            <div className="group bg-white dark:bg-slate-800 p-8 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-700 hover:border-primary/40 hover:shadow-xl transition-all duration-300 hover:-translate-y-2 animation-delay-100">
              <div className="bg-primary/10 w-12 h-12 rounded-xl flex items-center justify-center mb-6 group-hover:bg-primary group-hover:scale-110 transition-all duration-300">
                <BarChart3 className="h-6 w-6 text-primary group-hover:text-white" />
              </div>
              <h3 className="font-bold text-xl text-slate-900 dark:text-white mb-3">
                Progress Tracking
              </h3>
              <p className="text-slate-600 dark:text-slate-300 mt-3 leading-relaxed">
                Advanced analytics for teachers to monitor student engagement
                and performance metrics in real-time.
              </p>
            </div>

            {/* Online Exams */}
            <div className="group bg-white dark:bg-slate-800 p-8 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-700 hover:border-primary/40 hover:shadow-xl transition-all duration-300 hover:-translate-y-2 animation-delay-200">
              <div className="bg-primary/10 w-12 h-12 rounded-xl flex items-center justify-center mb-6 group-hover:bg-primary group-hover:scale-110 transition-all duration-300">
                <GraduationCap className="h-6 w-6 text-primary group-hover:text-white" />
              </div>
              <h3 className="font-bold text-xl text-slate-900 dark:text-white mb-3">
                Smart Assessments
              </h3>
              <p className="text-slate-600 dark:text-slate-300 mt-3 leading-relaxed">
                Dynamic quizzes that adapt difficulty levels based on your
                previous answers for a more efficient learning curve.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 bg-slate-900 dark:bg-slate-800">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-lg text-slate-300 mb-8 max-w-2xl mx-auto">
            Join thousands of students and teachers who are already experiencing
            the future of education with AI-powered personalized learning.
          </p>
          <Link
            href="/register"
            className="inline-flex items-center gap-2 bg-primary text-white px-8 py-4 rounded-xl font-semibold hover:bg-primary/90 transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-primary/25"
          >
            Get Started Today
            <ArrowRight className="h-5 w-5" />
          </Link>
        </div>
      </section>

      {/* Footer Info */}
      <footer className="py-12 border-t border-slate-200 dark:border-slate-800">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <span className="font-bold text-primary">AI-LMS</span>
            <span className="text-slate-500 dark:text-slate-400">© 2026 All rights reserved.</span>
          </div>
          <div className="text-slate-500 dark:text-slate-400 text-sm">
            Built with <span className="text-slate-900 dark:text-white font-medium">Next.js 16</span>,
            <span className="text-slate-900 dark:text-white font-medium"> Prisma 7</span>, and
            <span className="text-slate-900 dark:text-white font-medium"> Neon Postgres</span>.
          </div>
        </div>
      </footer>
    </div>
  );
}
