import Link from "next/link";
import { MoveRight, Bot, BarChart3, GraduationCap } from "lucide-react"; // I suggest using Lucide icons for a better look

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="relative pt-20 pb-16 md:pt-32 md:pb-24 overflow-hidden">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center space-y-8">
            <div className="inline-flex items-center rounded-full px-3 py-1 text-sm font-medium bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-700/10 mb-4">
              Now powered by Gemini 1.5 Pro
            </div>

            <h1 className="text-5xl md:text-7xl font-extrabold text-gray-900 tracking-tight">
              Adaptive <span className="text-blue-600">AI LMS</span>
            </h1>

            <p className="max-w-2xl mx-auto text-xl text-gray-600 leading-relaxed">
              Personalized learning paths generated by Google Gemini. Learn
              faster, smarter, and at your own pace with AI-tailored study
              plans.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
              <Link
                href="/register"
                className="inline-flex items-center justify-center bg-blue-600 text-white px-8 py-4 rounded-xl font-bold hover:bg-blue-700 transition-all shadow-lg hover:shadow-blue-200"
              >
                Start Learning Free
                <MoveRight className="ml-2 h-5 w-5" />
              </Link>
              <Link
                href="#features"
                className="inline-flex items-center justify-center bg-white text-gray-700 border border-gray-200 px-8 py-4 rounded-xl font-semibold hover:bg-gray-50 transition"
              >
                View Features
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Feature Cards Section */}
      <section id="features" className="py-24 bg-gray-50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid md:grid-cols-3 gap-8">
            {/* AI Study Plans */}
            <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:border-blue-300 transition-colors group">
              <div className="bg-blue-50 w-12 h-12 rounded-lg flex items-center justify-center mb-6 group-hover:bg-blue-600 transition-colors">
                <Bot className="h-6 w-6 text-blue-600 group-hover:text-white" />
              </div>
              <h3 className="font-bold text-xl text-gray-900">
                AI Study Plans
              </h3>
              <p className="text-gray-500 mt-3 leading-relaxed">
                Enter any topic and our Gemini integration creates a structured
                30-day roadmap tailored to your specific goals.
              </p>
            </div>

            {/* Teacher Insights */}
            <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:border-blue-300 transition-colors group">
              <div className="bg-blue-50 w-12 h-12 rounded-lg flex items-center justify-center mb-6 group-hover:bg-blue-600 transition-colors">
                <BarChart3 className="h-6 w-6 text-blue-600 group-hover:text-white" />
              </div>
              <h3 className="font-bold text-xl text-gray-900">
                Progress Tracking
              </h3>
              <p className="text-gray-500 mt-3 leading-relaxed">
                Advanced analytics for teachers to monitor student engagement
                and performance metrics in real-time.
              </p>
            </div>

            {/* Online Exams */}
            <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:border-blue-300 transition-colors group">
              <div className="bg-blue-50 w-12 h-12 rounded-lg flex items-center justify-center mb-6 group-hover:bg-blue-600 transition-colors">
                <GraduationCap className="h-6 w-6 text-blue-600 group-hover:text-white" />
              </div>
              <h3 className="font-bold text-xl text-gray-900">
                Smart Assessments
              </h3>
              <p className="text-gray-500 mt-3 leading-relaxed">
                Dynamic quizzes that adapt difficulty levels based on your
                previous answers for a more efficient learning curve.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Footer Info */}
      <footer className="py-12 border-t border-gray-100">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <span className="font-bold text-blue-600">AI-LMS</span>
            <span className="text-gray-400">© 2026 All rights reserved.</span>
          </div>
          <div className="text-gray-400 text-sm">
            Built with{" "}
            <span className="text-black font-medium">Next.js 16</span>,
            <span className="text-black font-medium"> Prisma 7</span>, and
            <span className="text-black font-medium"> Neon Postgres</span>.
          </div>
        </div>
      </footer>
    </div>
  );
}
